<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <VcpkgInstalledDir>C:\vcpkg\installed\x86-windows</VcpkgInstalledDir>
    <DepsDir>C:\deps</DepsDir>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(VcpkgInstalledDir)\include;$(VcpkgInstalledDir)\include\opus;$(VcpkgInstalledDir)\include\ogg;$(DepsDir)\include;$(DepsDir)\drift;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <PreprocessorDefinitions>DSL_STATIC;ENABLE_SSL;ABSL_CONSUME_DLL;PROTOBUF_USE_DLLS;_HAS_STD_BYTE=0;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <LanguageStandard>stdcpp17</LanguageStandard>
    </ClCompile>
    <Link>
      <AdditionalLibraryDirectories>$(VcpkgInstalledDir)\lib;$(DepsDir)\lib;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
      <AdditionalDependencies>ibdsl.lib;libvorbisenc.lib;libprotobuf.lib;abseil_dll.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
  </ItemDefinitionGroup>
</Project>
